# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-mlsmanager

# >> macros
# << macros

Summary:    MLS Manager
Version:    0.2.4
Release:    1
Group:      Location/Location Framework
License:    MIT
URL:        https://github.com/black-sheep-dev/harbour-mlsmanager
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-mlsmanager.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   nemo-qml-plugin-notifications-qt5
Requires:   nemo-qml-plugin-dbus-qt5
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.3
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(nemonotifications-qt5)
BuildRequires:  qt5-qttools-linguist
BuildRequires:  desktop-file-utils

%description
Manager for Mozilla Location Service offline packages for Sailfish OS

%if "%{?vendor}" == "chum"
PackageName: MLS Manager
Type: desktop-application
Categories:
  - Map
  - Utility
Custom:
  DescriptionMD: https://github.com/black-sheep-dev/harbour-mlsmanager/raw/master/README.md
  Repo: https://github.com/black-sheep-dev/harbour-mlsmanager/
Icon: https://raw.githubusercontent.com/black-sheep-dev/harbour-mlsmanager/master/icons/harbour-mlsmanager.svg
Screenshots:
  - https://github.com/black-sheep-dev/harbour-mlsmanager/raw/master/metadata/screenshot1.png
  - https://github.com/black-sheep-dev/harbour-mlsmanager/raw/master/metadata/screenshot2.png
Url:
  Donation: https://www.paypal.com/paypalme/nubecula/1
%endif


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%{_datadir}/mapplauncherd/privileges.d/%{name}.privileges
%{_datadir}/dbus-1/services/harbour.mlsmanager.service
# >> files
# << files
