#ifndef COUNTRY_H
#define COUNTRY_H

#include <QObject>
#include <QString>
#include <QMap>

static QMap<QString, QString> names = {
    {QStringLiteral("ad"), QObject::tr("Andorra")},
    {QStringLiteral("al"), QObject::tr("Albania")},
    {QStringLiteral("am"), QObject::tr("Armenia")},
    {QStringLiteral("ao"), QObject::tr("Angola")},
    {QStringLiteral("at"), QObject::tr("Austria")},
    {QStringLiteral("au"), QObject::tr("Australia")},
    {QStringLiteral("ax"), QObject::tr("Aland Islands")},
    {QStringLiteral("az"), QObject::tr("Azerbaijan")},
    {QStringLiteral("ba"), QObject::tr("Bosnia and Herzegovina")},
    {QStringLiteral("be"), QObject::tr("Belgium")},
    {QStringLiteral("bf"), QObject::tr("Burkina Faso")},
    {QStringLiteral("bg"), QObject::tr("Bulgaria")},
    {QStringLiteral("bi"), QObject::tr("Burundi")},
    {QStringLiteral("bj"), QObject::tr("Benin")},
    {QStringLiteral("bw"), QObject::tr("Botswana")},
    {QStringLiteral("by"), QObject::tr("Belarus")},
    {QStringLiteral("cd"), QObject::tr("Democratic Republic of the Congo")},
    {QStringLiteral("cf"), QObject::tr("Central African Rebublic")},
    {QStringLiteral("cg"), QObject::tr("Congo")},
    {QStringLiteral("ch"), QObject::tr("Switzerland")},
    {QStringLiteral("cm"), QObject::tr("Cameroon")},
    {QStringLiteral("cv"), QObject::tr("Cap Verde")},
    {QStringLiteral("cy"), QObject::tr("Cyprus")},
    {QStringLiteral("cz"), QObject::tr("Czech Republic")},
    {QStringLiteral("de"), QObject::tr("Germany")},
    {QStringLiteral("dj"), QObject::tr("Djibouti")},
    {QStringLiteral("dk"), QObject::tr("Denmark")},
    {QStringLiteral("dz"), QObject::tr("Algeria")},
    {QStringLiteral("ee"), QObject::tr("Estonia")},
    {QStringLiteral("eg"), QObject::tr("Egypt")},
    {QStringLiteral("er"), QObject::tr("Eritrea")},
    {QStringLiteral("es"), QObject::tr("Spain")},
    {QStringLiteral("et"), QObject::tr("Ethiopia")},
    {QStringLiteral("fi"), QObject::tr("Finland")},
    {QStringLiteral("fo"), QObject::tr("Faroe Islands")},
    {QStringLiteral("fr"), QObject::tr("France")},
    {QStringLiteral("ga"), QObject::tr("Gabon")},
    {QStringLiteral("gb"), QObject::tr("United Kingdom")},
    {QStringLiteral("gg"), QObject::tr("Guernsey")},
    {QStringLiteral("gh"), QObject::tr("Ghana")},
    {QStringLiteral("gi"), QObject::tr("Gibraltar")},
    {QStringLiteral("gm"), QObject::tr("Gambia")},
    {QStringLiteral("gn"), QObject::tr("Guinea")},
    {QStringLiteral("gq"), QObject::tr("Equatorial Guinea")},
    {QStringLiteral("gr"), QObject::tr("Greece")},
    {QStringLiteral("gw"), QObject::tr("Guinea Bissau")},
    {QStringLiteral("hr"), QObject::tr("Croatia")},
    {QStringLiteral("hu"), QObject::tr("Hungary")},
    {QStringLiteral("ie"), QObject::tr("Ireland")},
    {QStringLiteral("im"), QObject::tr("Isle of Man")},
    {QStringLiteral("in"), QObject::tr("India")},
    {QStringLiteral("is"), QObject::tr("Iceland")},
    {QStringLiteral("it"), QObject::tr("Italy")},
    {QStringLiteral("je"), QObject::tr("Jersey")},
    {QStringLiteral("ke"), QObject::tr("Kenya")},
    {QStringLiteral("km"), QObject::tr("Comoros")},
    {QStringLiteral("kz"), QObject::tr("Kazakhstan")},
    {QStringLiteral("li"), QObject::tr("Liechtenstein")},
    {QStringLiteral("lr"), QObject::tr("Liberia")},
    {QStringLiteral("ls"), QObject::tr("Lesotho")},
    {QStringLiteral("lt"), QObject::tr("Lithuania")},
    {QStringLiteral("lu"), QObject::tr("Luxembourg")},
    {QStringLiteral("lv"), QObject::tr("Latvia")},
    {QStringLiteral("ly"), QObject::tr("Lybia")},
    {QStringLiteral("ma"), QObject::tr("Morocco")},
    {QStringLiteral("mc"), QObject::tr("Monaco")},
    {QStringLiteral("md"), QObject::tr("Moldova")},
    {QStringLiteral("me"), QObject::tr("Montenegro")},
    {QStringLiteral("mg"), QObject::tr("Madagascar")},
    {QStringLiteral("mk"), QObject::tr("North Macedonia")},
    {QStringLiteral("ml"), QObject::tr("Mali")},
    {QStringLiteral("mr"), QObject::tr("Mauritania")},
    {QStringLiteral("mt"), QObject::tr("Malta")},
    {QStringLiteral("mu"), QObject::tr("Mauritius")},
    {QStringLiteral("mw"), QObject::tr("Malawi")},
    {QStringLiteral("mz"), QObject::tr("Mozambique")},
    {QStringLiteral("na"), QObject::tr("Namibia")},
    {QStringLiteral("ne"), QObject::tr("Niger")},
    {QStringLiteral("ng"), QObject::tr("Nigera")},
    {QStringLiteral("nl"), QObject::tr("Netherlands")},
    {QStringLiteral("no"), QObject::tr("Norway")},
    {QStringLiteral("pl"), QObject::tr("Poland")},
    {QStringLiteral("pt"), QObject::tr("Portugal")},
    {QStringLiteral("re"), QObject::tr("Reunion")},
    {QStringLiteral("ro"), QObject::tr("Romania")},
    {QStringLiteral("rs"), QObject::tr("Serbia")},
    {QStringLiteral("ru"), QObject::tr("Russia")},
    {QStringLiteral("rw"), QObject::tr("Rwanda")},
    {QStringLiteral("sc"), QObject::tr("Seychelles")},
    {QStringLiteral("sd"), QObject::tr("Sudan")},
    {QStringLiteral("se"), QObject::tr("Sweden")},
    {QStringLiteral("si"), QObject::tr("Slovenia")},
    {QStringLiteral("sk"), QObject::tr("Slovakia")},
    {QStringLiteral("sl"), QObject::tr("Sierra_Leone")},
    {QStringLiteral("sm"), QObject::tr("San Marino")},
    {QStringLiteral("sn"), QObject::tr("Senegal")},
    {QStringLiteral("so"), QObject::tr("Somalia")},
    {QStringLiteral("ss"), QObject::tr("South Sudan")},
    {QStringLiteral("st"), QObject::tr("Sao Tome and Principe")},
    {QStringLiteral("td"), QObject::tr("Chad")},
    {QStringLiteral("tg"), QObject::tr("Togo")},
    {QStringLiteral("tz"), QObject::tr("Tanzania")},
    {QStringLiteral("ua"), QObject::tr("Ukraine")},
    {QStringLiteral("ug"), QObject::tr("Uganda")},
    {QStringLiteral("yt"), QObject::tr("Mayotte")},
    {QStringLiteral("za"), QObject::tr("South Africa")},
    {QStringLiteral("zm"), QObject::tr("Zambia")},
    {QStringLiteral("zw"), QObject::tr("Zimbabwe")}
};

struct Country
{
    static QString name(const QString &code){
        return names.value(code, code);
    }
};

#endif // COUNTRY_H
